### ISSUE TITLE
Cover is being calculated from the center of the token rather than one of the corners

### ISSUE THREAD

**Issue by Zamrod** [caewok/fvtt-token-cover#11]
![image](https://github.com/caewok/fvtt-token-cover/assets/12570777/d9197465-0a4b-46cb-ad63-4040fa8609ad)

I have both ATC and ATV set to DND5e DMG. This picture shows the debug from ATV's line of sight. There is one green line to the corner of the target square, meaning that there should be 3/4 cover.

![image](https://github.com/caewok/fvtt-token-cover/assets/12570777/e380810c-79b9-47f0-8039-980f2bf25fc7)

If you debug ATC, however, it shows all the lines blocked since they come from the center.

![image](https://github.com/caewok/fvtt-token-cover/assets/12570777/a3360f50-c8b1-4f05-b6e8-54dada946e8f)

**Comment by Zamrod** [comment]
I've tested and this appears to happen regardless of the setting. It seems to ignore the setting.

Also, it only measures to the center of the target token regardless of the setting as well:

![image](https://github.com/caewok/fvtt-token-cover/assets/12570777/c3f9b6f5-cd84-4235-8d4d-18db0ecfd0a4)

**Comment by caewok** [comment]
Fixed in v0.6.5.
