### ISSUE TITLE
[Bug] Reset to Pf2e option doesn't work

### ISSUE THREAD

**Issue by weepingminotaur** [caewok/fvtt-token-cover#19]
Clicking the button returns this console errror. 
<img width="557" alt="Screenshot 2024-02-12 at 5 52 11 PM" src="https://github.com/caewok/fvtt-token-cover/assets/90105219/1beab25d-950b-42f0-b0ed-9c8191d4212f">

**Comment by caewok** [comment]
Fixed in 0.7.4.
