### ISSUE TITLE
Unable to Place, Move, or Remove Tokens

### ISSUE THREAD

**Issue by Quasxen** [caewok/fvtt-token-cover#20]
Just updated to version 0.7.0 and now I'm unable to do anything with a token with this module turned on. When simply clicking on a token I get the following:
![image](https://github.com/caewok/fvtt-token-cover/assets/166070156/88691f4f-0791-4361-bbd5-e4cac3aa0b76)

When trying to click and drag a token to move it, I get the following errors:
![image](https://github.com/caewok/fvtt-token-cover/assets/166070156/5c5cd551-372e-4aba-b8fb-5d18e5fe016b)

Decided to try things with ALL modules off except this one and its dependencies and clicking on a token gives:
![image](https://github.com/caewok/fvtt-token-cover/assets/166070156/e2f711ae-e80f-4ca7-a454-8cac1862a8b9)

Hopefully all this information is helpful and not overloading things. While still having all modules off except this on, with token selected I hit an arrow key to get the following error and the token doesn't move:
![image](https://github.com/caewok/fvtt-token-cover/assets/166070156/4ea8cf86-bbfa-44bb-8ea9-761fbbc09233)

**Comment by Quasxen** [comment]
Was talking to my friend that knows JS and he gave the following sample as an idea for how to help prevent something like this:
![image](https://github.com/caewok/fvtt-token-cover/assets/166070156/fc1c2113-22f7-4fd9-aa6b-26dd659edabd)

**Comment by caewok** [comment]
Someone in Discord had the same errors. Try uninstalling the module in Foundry. Then reinstall it, which should get you the 0.6.5 version. Then update that, which should get you to v0.7.0. You might also want to first try without any other modules running. If you find a compatibility issue with a specific module, please open a new Git issue detailing what other module you are using. Thanks!

Thanks for the tip, but I have full control of the map in that error, and it should exist. So modifying map as your friend suggested would only hide the error, not really resolve it in this case.

**Comment by Quasxen** [comment]
Version 0.6.5 works perfectly fine. It was when I updated to v0.7.0 that the error occurs. I also turned off all modules (mentioned this in original post) and still got the error and issue.

Until there's a v0.7.1, I'll be forced to stick with v0.6.5
