### ISSUE TITLE
Cover is not being calculated

### ISSUE THREAD

**Issue by Stonedtroll** [caewok/fvtt-token-cover#30]
Cover is not being calculated. The error I see in the console after initiating an attack but not yet rolling for the attack:

![Screenshot 2024-08-19 at 9 55 28 PM](https://github.com/user-attachments/assets/6433d329-7409-4daa-9a40-324138333fa2)

The attack continues but AC is not adjusted for cover. Target is standing behind a 3ft wall. Have adjusted it to 5ft with the same result.

If I enable midiQOL to Calculate Cover using Alternate Token Cover, I get

![Screenshot 2024-08-19 at 10 53 09 PM](https://github.com/user-attachments/assets/c1e5222d-b85e-4b70-bec2-cf713aa08ec7)

An no attack card appears in the chat.

I saw the other bug report RE: Wall Templates and removed the module but same error.

Interestingly, if I enabled "Use Token Icon Only", the icon is displayed with no error. 

I'm running v12 build 331 with D&D 3.3.1

Thank you!

**Comment by caewok** [comment]
This is a DFred's compatibility issue. Addressed in v0.9.3.
