### ISSUE TITLE
No GM Prompt

### ISSUE THREAD

**Issue by MythicalRollers** [caewok/fvtt-token-cover#37]
FoundryVTT: 12.331
D&D5e: 3.3.1
ATC:  0.9.6
DAE: 11.3.64
lib: 1.13.2.0
Midi: 11.6.19.1
socket: 1.1.0

Confirm cover set to Ask GM.  It does not prompt.  V11 8.0.3, this prompt worked great.  I've updated to V12, and updated to the last version of ATC, and the prompt never happens.  Midi settings are set to use ATC, but it seems to be auto adding the cover and not giving GM the choice.
If I turn all modules off except for ATC and dependencies, the prompt works. When I turn midi and DAE on, it does not. 
![image](https://github.com/user-attachments/assets/1ee95cae-7daf-48c5-8253-e32369d86b9a)
![image](https://github.com/user-attachments/assets/75ef8de5-eb79-4cf4-b007-dbd5490c033f)

**Comment by caewok** [comment]
Yep, should be fixed in v0.9.8. Thanks!
