### ISSUE TITLE
PF2e: Error in CoverFlagEffect._initializeStorageMap

### ISSUE THREAD

**Issue by Eligarf** [caewok/fvtt-token-cover#38]
Happens on every load/reload.
Repro with just PF2e system 6.4.1 and only tokencover 0.9.6 enabled

foundry.js:655  Error: PF2e System | Item type base does not exist and item module sub-types are not supported
[Detected 2 packages: system:pf2e(6.4.1), tokencover(0.9.6)]
    at ErrorPF2e (pf2e.mjs:1:8618)
    at Object.construct (pf2e.mjs:1580:229094)
    at #preCreateDocumentArray (foundry-esm.js:56385:17)
    at ClientDatabaseBackendPF2e._createDocuments (foundry-esm.js:56347:58)
    at ClientDatabaseBackendPF2e.create (foundry-esm.js:12281:19)
    at async Proxy.createDocuments (foundry-esm.js:11423:23)
    at async Proxy.create (foundry-esm.js:11567:23)
    at async createDocument (documents.js:33:15)
    at async CoverFlagEffect._initializeStorageMap (UniqueActiveEffect.js:219:20)
    at async CoverFlagEffect.initialize (AbstractUniqueEffect.js:667:5)
onError @ foundry.js:655
🎁Hooks.onError#0 @ libWrapper-wrapper.js:188
#preCreateDocumentArray @ foundry-esm.js:56387
_createDocuments @ foundry-esm.js:56347
create @ foundry-esm.js:12281
await in create
createDocuments @ foundry-esm.js:11423
createDocuments @ pf2e.mjs:1580
create @ foundry-esm.js:11567
createDocument @ documents.js:33
_initializeStorageMap @ UniqueActiveEffect.js:219
initialize @ AbstractUniqueEffect.js:667
(anonymous) @ module.js:96
#call @ foundry.js:632
callAll @ foundry.js:589
setupGame @ foundry.js:9098
await in setupGame
_initializeGameView @ foundry.js:10432
_initializeView @ foundry.js:10408
initialize @ foundry.js:8995
await in initialize
🎁Game.prototype.initialize#0 @ libWrapper-wrapper.js:188
(anonymous) @ foundry.js:95974
foundry.js:72076  PF2e System | Item type base does not exist and item module sub-types are not supported
[Detected 2 packages: system:pf2e(6.4.1), tokencover(0.9.6)]

**Comment by mindcloud69** [comment]
I get this same error exactly.

**Comment by caewok** [comment]
I addressed this error in v0.9.7. It appears to occur only on new worlds; presumably existing worlds migrated the item at issue and so I did not see it until I created a brand new world. PF2e does a lot of things its own way, so I would expect more issues as I don't have a ton of experience in that system and not a lot of time to mess around in it. Feel free to open other issues as you find them.

**Comment by Eligarf** [comment]
It fixed my issue, thanks!
