### ISSUE TITLE
ATC is not firing the underlying status condition

### ISSUE THREAD

**Issue by Stonedtroll** [caewok/fvtt-token-cover#46]
Or rather, I am assuming it's not because the AC is not being changed. The cover is being calculated correctly.

![image](https://github.com/user-attachments/assets/30dfc11d-2b85-48b4-ac5a-67f8b410db52)

I had "Reset Default Cover".

Steps to reproduce:
1. Attack a target in cover.
2. Check that the correct AE icon is displayed.
3. Check the AC. 
4. Observe the AC. It is not modified.
5. Manually set the cover status.
6. Attack the target
7. Check the AC
8. Observe the AC. It is correctly modified.

So the cover status is working correctly. It appears that ATC is not firing the status.

I checked the Cover Effect and it has the correct status.
 
![image](https://github.com/user-attachments/assets/5305310b-dc7c-48d1-af61-95ff423b7a4d)

Foundry 12.331
DND5e 4.1.2
ATC 0.9.8

**Comment by caewok** [comment]
Sorry about that! Try v0.9.9.
